Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -45,7 +45,6 @@ jobs:
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         passphrase: ${{ secrets.SSH_PASSPHRASE }}
         script: |
-          # Kiểm tra và cài đặt Docker nếu chưa có
           if ! command -v docker &> /dev/null; then
             echo "Docker not found. Installing Docker..."
             sudo apt-get update
@@ -56,18 +55,18 @@ jobs:
           fi
 
           if ! command -v docker-compose &> /dev/null; then
-            sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.7/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-            sudo chmod +x /usr/local/bin/docker-compose
+            echo "Docker Compose not found. Please install it manually."
+            exit 1
           fi
 
-          mkdir -p ~/tranquoccuong
           cd ~/tranquoccuong
 
           cat <<EOF > ~/tranquoccuong/docker-compose.yml
           version: '3.8'
           services:
-            timelypm-be:
+            app:
               image: tranquoccuong/timelypm-be:latest
+              container_name: TimelyPM
               ports:
                 - "8080:8080"
               environment:
